### ISSUE TITLE
Consider setting `meta.docs.url` for rules

### ISSUE THREAD

**Issue by nikolay-borzov** [Yash-Singh1/eslint-plugin-userscripts#46]
It would be helpful to navigate to rule's doc page from IDE.

![image](https://user-images.githubusercontent.com/4221449/167799293-52460fe5-a88a-4a10-9091-6cf75b91e321.png)

I wonder how rule sets like [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn) manage to provide doc links w/o having `meta.docs.url` set. Maybe there is some directory structure convention - can't figure out

**Comment by Yash-Singh1** [comment]
Yes, this will be useful for using the linter in the code editor.

> I wonder how rule sets like [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn) manage to provide doc links w/o having `meta.docs.url` set. Maybe there is some directory structure convention - can't figure out

Eslint plugin unicorn loads the rules and adds in the url prop separately because so the format can be managed from one place, over here: 

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/57bd00eb95f0fca7f1420bd206e1b85ef5750eb1/rules/utils/rule.js#L126

**Comment by Yash-Singh1** [comment]
Fixed in 702a391809ef0fc0a5ea9ea641f42c5dd4de8ac5.
