### ISSUE TITLE
Process only javascript files

### ISSUE THREAD

**Issue by vanowm** [Yash-Singh1/eslint-plugin-userscripts#90]
When `eslint-plugin-json-schema-validator` installed, EPU is trying process `.json` files too:
![image](https://github.com/Yash-Singh1/eslint-plugin-userscripts/assets/511517/db76e31c-4f36-4d9a-b800-5173b5b329bc)

**Comment by Yash-Singh1** [comment]
Configuring file extensions are usually taken care of by the users, so if you want to run EPU on only .js files, then you can have an override:

```js
// .eslintrc.js
module.exports = {
  overrides: [
    {
      files: '**/*.js',
      extends: ['plugin:userscripts/recommended']
    }
  ]
};
```

This would do a configuration override on all files that end with .js to extend EPUs recommended config, so that it doesn't run on .json files. LMK if that works.

**Comment by vanowm** [comment]
So, EPO is no aware of the type of file it's processing?

Thanks for the work around suggestion, it worked.

**Comment by Yash-Singh1** [comment]
> So, EPO is no aware of the type of file it's processing?

While we could validate the file extension of the linted file, many ESLint plugins tend to skip this step. There's a variety of file extensions that users like to use, and trying to keep track of all of them could be hard.

> Thanks for the work around suggestion, it worked.

Perfect! I'll close the issue.
